### ISSUE TITLE
Goroutine crash in communities

### ISSUE THREAD

**Issue by TimothyCole** [SocialBlade/Discord-Bot#2]
```
goroutine 12855 [running]:
_/(redacted)/helpers.GetCommunities(0xc42009ac60, 0xc42000e4c8, 0xc4200dd880, 0xc4200dd8a0, 0xc4200dd8c0, 0xc4200dd8e0, 0xc4200dd900, 0xc4200dd920)
        /(redacted)/helpers/communities.go:17 +0x8f
_/(redacted)/helpers.Communities(0xc42009ac60, 0xc42000e4c8)
        /(redacted)/helpers/communities.go:50 +0x50
created by _/(redacted)/helpers.MessageCreateHandler
        /(redacted)/helpers/messages.go:64 +0x6f3
exit status 2
```

**Comment by TimothyCole** [comment]
Fixed by https://github.com/SocialBlade/Discord-Bot/commit/9d7c4e29d2ecfccfd33f7bbcd5e61e085256d6ed#diff-d7c77dfd0c862b26f3a4d30a67aaf4abR18
